project:
  type: website
  output-dir: docs

website:
  title: "Dawei Wang"
  navbar:
    background: "#135A7D"
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: cv.qmd
        text: CV
      - contact.qmd
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/daweiwang365/
      - icon: github
        href: https://github.com/dw20yy
  page-footer: 
    left: 
      "© 2026, Dawei Wang"
    border: false
    background: "#C0C8C4"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

